### ISSUE TITLE
Enable the interactive shell

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scipy.org-new#11]
I am not sure how the binder stuff is configured or works.  So I am not sure what is needed to get it working.

Perhaps `content/getting-started-example.py` should be moved to `layouts/partials/shell-lesson.html`.  I am not sure the old site is serving `content/getting-started-example.py` and `content/getting-started-plot.png`.

**Comment by rossbar** [comment]
FWIW the interactive terminal on `numpy.org` has never worked well for me, and I know others have had problems as well. I'm going to open an issue there as well to highlight my specific experience, but honestly in it's current state I don't necessarily think the interactive terminal is an improvement to the site.

**Comment by stefanv** [comment]
I agree; I think we'd be better of taking it out.

**Comment by rossbar** [comment]
I opened an issue at numpy/numpy.org#466 with some of the specifics that make it difficult to use IME.

**Comment by jarrodmillman** [comment]
Removed in #13.
